spring.application.name=techstore-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/techstore}
spring.datasource.username=${DB_USERNAME:techstore}
spring.datasource.password=${DB_PASSWORD:techstore}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

app.security.username=${APP_SECURITY_USERNAME:local-admin@example.com}
app.security.password=${APP_SECURITY_PASSWORD:change-me-local-password}

jwt.secret=${JWT_SECRET:change-this-jwt-secret-in-env-2026}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

aws.region=${AWS_REGION:us-east-1}
aws.sqs.audit-queue-url=${AUDIT_QUEUE_URL:}
